#
# Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "README.md"]

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl:

####################################
######   Optional Features    ######
####################################
smooth-scroll: true

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

#######################################################
#######################################################
###############   HEADER INFORMATION   ################
#######################################################
#######################################################

# This is your site title
title: Oxymoronic Software Solutions
# Website language
lang: en-US
# Header Title
header-title:  Imagine Develop Inspire
# Header Tagline
headter-tagline: Insert typing JS file here


#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: gamernaut19@gmail.com

####################################
######  Global Social Links   ######
####################################
youtube: '#'
pinterest: '#'
facebook: '#'
twitter: '#'
google-plus: '#'
vimeo: '#'


####
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Welcome
about-description: I'm a hobbyist programmer who has been away from programming for many years and is starting to get back into it now. I'm completely self taught (having started with BASIC in the 80s) and devour anything I can find in books, on the web or in other peoples code to increase my knowledge. I'm currently learning/relearning C++ and Python and will probably add Kotlin, PHP and Javascript to my list eventually.

#####################################
############  Portfolio  ############
#####################################
portfolio-title: Portfolio
portfolio-description: Learning to code is like learning a natural language, you need to know how to use the (key)words as much as what words to use when. My favourite coding projects are below. Click on a category to filter the projects.

#
# Portfolio Grid
#
portfolio-categories: [Python, Cpp, Bioinformatics, Games, Flight Simulation, Big Data]
portfolio:

# Portfolio Item
- title: R<span class="thin">egulon</span>
  categories: [Python, Bioinformatics]
  image: img-01.jpg
  url: 'https://github.com/Gamernaut/Regulon'

# Portfolio Item
- title: B<span class="thin">MS</span> Shortest Distance 
  categories: [Flight Simulation, Python]
  image: img-02.jpg
  url: 'https://github.com/Gamernaut/BMS_Visit_all_Airfields'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Cpp]
  image: img-03.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Python, Video, Photography]
  image: img-04.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Big Data]
  image: img-05.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Development, Video]
  image: img-06.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Python, Graphic Design]
  image: img-07.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Python , Video]
  image: img-08.jpg
  url: '#'

# Portfolio Item
- title: S<span class="thin">era</span> Style
  categories: [Games]
  image: img-09.jpg
  url: '#'


#####################################
############   Contact   ############
#####################################
contact-title: Contact Me
contact-description: Get in touch if you like what you see.


#####################################
#############   Footer   ############
#####################################
footer-description: 
footer-copyright-text: 
footer-copyright-url:
footer-copyright-year:
