#
# Sera - OnePage Jekyll Template
# Configuration File
#

# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "README.md"]

#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl:

####################################
######   Optional Features    ######
####################################
smooth-scroll: true

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

#######################################################
#######################################################
###############   HEADER INFORMATION   ################
#######################################################
#######################################################

# This is your site title
title: Carmelo Volpe - Programmer
# Website language
lang: en-US
# Header Title
header-title: Carmelo Volpe
# Header Tagline
header-tagline: 


#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: gamernaut19@gmail.com

####################################
######  Global Social Links   ######
####################################
youtube: '#'
pinterest: '#'
facebook: '#'
twitter: '#'
google-plus: '#'
vimeo: '#'


####
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: About 
about-description: I started writing software on a VIC-20 in the mid 80's and have been hooked ever since. I'm completely self taught (having started with BASIC in the 80s) and devour anything I can find in books, on the web or in other peoples code to increase my knowledge. I have a background in the sciences and an engineering mindset and am a natural problem solver. I'd love to build some kind of Space/Flight simulator, which I see as an ongoing lifetime project. I also enjoying learning about algoritms and how more advanced algorithms (AI/ML, Genetic Algorithms etc.) can be applied biological scientific problems. See my portfolio below for a few examples of what I can do.

#####################################
############  Portfolio  ############
#####################################
portfolio-title: Portfolio
portfolio-description: Programming to me is very much like my scientific apporach. Its about solving a real world problem using abstract and imaginitive thinking applied in a structured way to solve a concrete problem. Some of my projects are below, click on a category to filter the projects.

#
# Portfolio Grid
#
portfolio-categories: [Python, Cpp, Bioinformatics, Flight Simulation, ML and AI]
portfolio:

# Portfolio Item
- title: R<span class="thin">egulon</span>
  categories: [Python, Bioinformatics]
  image: Bioinformatics2.jpg
  url: 'https://github.com/Gamernaut/Regulon'

# Portfolio Item
- title: B<span class="thin">MS</span> Shortest Distance 
  categories: [Flight Simulation, Python]
  image: img-02.jpg
  url: 'https://github.com/Gamernaut/BMS_Visit_all_Airfields'

# Portfolio Item
- title: S<span class="thin">A Trainer</span> Style
  categories: [Flight Simulation, Cpp]
  image: img-03.jpg
  url: 'https://github.com/Gamernaut/SA_Trainer'


#####################################
############   Contact   ############
#####################################
contact-title: Contact Me
contact-description: Get in touch if you like what you see.


#####################################
#############   Footer   ############
#####################################
footer-description: 
footer-copyright-text: Gamernaut
footer-copyright-url:
footer-copyright-year: 2021
